update JenkinsFile
Fantom-foundation/Aida pull request #1091
Opened 2024-04-25 03:27 UTC by wsodsong

## Description

Update Jenkins test for the new test infrastructure

## Type of change

Please delete options that are not relevant.

- [x] Adds or updates testing

2024-04-26 12:36 UTC, Lubomir-Jahn requested changes

2024-04-26 12:36 UTC, Lubomir-Jahn commented on Jenkinsfile
> +        DBSRC = '--db-src=${TMPDB}/state_db_carmen_go-file_${TOBLOCK}'
The PR fails on Jenkins because DBSRC variable will resolve in `--db-src=--db-tmp=/mnt/aida-statedb-disk/state_db_carmen_go-file_4600000`

2024-04-26 12:37 UTC, Lubomir-Jahn commented
In addition unit tests are failing for some reason 
https://scala.fantom.network/job/Aida/job/Aida-Pull-Request/view/change-requests/job/PR-1091/7/execution/node/42/log/

2024-05-01 06:38 UTC, petr-hanzl approved these changes
Thanks for the PR testing!

2024-05-01 08:36 UTC, Lubomir-Jahn approved these changes

2024-05-01 09:13 UTC, merged