support new statedb operations in tracer tools
Fantom-foundation/Aida pull request #1131
Opened 2024-07-09 08:03 UTC by wsodsong

## Description

Support the new statedb operations in `aida-sdb` tool.

Fixes #1122 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Adds or updates testing

2024-07-18 19:54 UTC, petr-hanzl requested changes

2024-07-18 19:54 UTC, petr-hanzl commented on stochastic/operation.go
> +	SelfDestruct6780ID:  "SelfDestruct6890",
```suggestion
	SelfDestruct6780ID:  "SelfDestruct6780",
```

2024-07-18 19:54 UTC, petr-hanzl commented on stochastic/replay.go
> +	selfdestructed []int64                   // list of self destructed accounts
```suggestion
	selfDestructed []int64                   // list of self destructed accounts
```

2024-07-18 19:54 UTC, petr-hanzl commented on tracer/operation/createcontract.go
`createcontract.go` -> `create_contract.go`

2024-07-19 02:57 UTC, wsodsong commented on tracer/operation/createcontract.go
All files in this folder are named without space. Just to name a few, addbalance.go, subbalance.go, etc.

2024-07-19 07:15 UTC, petr-hanzl commented on tracer/operation/createcontract.go
ic. Should we rename them all? In `go` it is normal to use `_` when naming files with more words.

2024-07-19 07:45 UTC, petr-hanzl approved these changes, later dismissed
Please check the documentation of `CreateAccount` and `GetStorageRoot` in `tracer`. Otherwise LGTM! Thanks!

2024-07-19 07:45 UTC, petr-hanzl commented on tracer/operation/getstorageroot.go
> +func (op *GetStorageRoot) Debug(ctx *context.Context) {
Documentation seems to be incorrect here (`get-code-hash` -> `get-storage-root`).

2024-07-19 07:45 UTC, petr-hanzl commented on tracer/operation/createcontract.go
> +}
Documentation seems to be incorrect here (`create-account` -> `create-contract`)?

2024-07-19 08:10 UTC, wsodsong commented on tracer/operation/createcontract.go
> +}
Thank you for pointing this out! Fixed!

2024-07-19 08:10 UTC, wsodsong commented on tracer/operation/getstorageroot.go
> +func (op *GetStorageRoot) Debug(ctx *context.Context) {
Fixed!

2024-07-19 08:12 UTC, petr-hanzl approved these changes

2024-07-19 09:07 UTC, merged