Fix geth tests
Fantom-foundation/Aida pull request #1160
Opened 2024-09-10 14:06 UTC by cabrador

## Description

This PR fixes file iteration by
1) correctly adding information to each tests such as description
2) adding expected error - some tests are designed to fail
and `blockEnviroment` of gethTests by correctly calculating each value depending on which fork is test running.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

2024-09-11 10:57 UTC, wsodsong submitted a review, later dismissed

2024-09-11 10:57 UTC, wsodsong commented on ethtest/state_test_context.go
> +		postNumber:    postNumber,
nit: it would be helpful if you can add short descriptions of these variables. What is postNumber?

2024-09-16 10:18 UTC, wsodsong requested changes

2024-09-16 10:18 UTC, wsodsong commented on ethtest/block_enviroment.go
> +	}
This code block read as if a block is London or later and `Random` is given, set difficult to 0.
Just want to confirm if `London` fork correct, not `Paris` (the merge)?

2024-09-16 10:18 UTC, wsodsong commented on ethtest/test_case_splitter_test.go
> +	tests, err := d.SplitStateTests()
```suggestion
	testsuite := TestCaseSplitter{
		jsons:        []*stJSON{stJson},
		log:          logger.NewLogger("info", "test-case-splitter-test"),
		chainConfigs: make(map[string]*params.ChainConfig),
	}
	tests, err := testsuite.SplitStateTests()
```

2024-09-16 10:18 UTC, wsodsong commented on ethtest/state_test_context.go
> +func newStateTestTxContest(stJson *stJSON, msg *core.Message, post stPost, chainCfg *params.ChainConfig, fork string, postNumber int) txcontext.TxContext {
```suggestion
func newStateTestTxContext(stJson *stJSON, msg *core.Message, post stPost, chainCfg *params.ChainConfig, fork string, postNumber int) txcontext.TxContext {
```

2024-09-16 10:18 UTC, wsodsong commented on ethtest/test_case_splitter.go
> +				})
I feel `ctx` is too generic. 
```suggestion
				txCtx := newStateTestTxContest(stJson, msg, post, chainCfg, fork, postNumber)
				dividedTests = append(dividedTests, Transaction{
					fork,
					txCtx,
				})
```

2024-09-16 10:18 UTC, wsodsong commented on ethtest/test_case_splitter.go
> +	cfg, _, err := tests.GetChainConfig(fork)
Is there a different between Ethereum chain config form our version of go-ethereum to the one used in `tests` package?

2024-09-16 13:32 UTC, cabrador commented on ethtest/block_enviroment.go
> +	}
This comes from [this](https://github.com/ethereum/go-ethereum/blob/ec596e06a58f3c4c4bac0262ebfc57539c3e5fd1/tests/state_test_util.go#L288) line.

2024-09-16 13:39 UTC, cabrador commented on ethtest/test_case_splitter.go
> +	cfg, _, err := tests.GetChainConfig(fork)
This is a special `chainConfig` created for the `tests` package. It aligns with the block setup in the `stBlockEnvironment`. You can check out the func [here](https://github.com/ethereum/go-ethereum/blob/ec596e06a58f3c4c4bac0262ebfc57539c3e5fd1/tests/state_test_util.go#L142).

The key part is this [map](https://github.com/ethereum/go-ethereum/blob/ec596e06a58f3c4c4bac0262ebfc57539c3e5fd1/tests/init.go#L30) used on line 148.

Every time `IsSomeFork()` (ie `IsLondon()`, `IsCancun()`, etc...) is used, it specifically asks for values from this map.

2024-09-16 13:40 UTC, cabrador commented on ethtest/test_case_splitter_test.go
> +	tests, err := d.SplitStateTests()
mb - I forgot to rename this. I will use splitter if you are fine with this name

2024-09-17 05:14 UTC, wsodsong approved these changes
Looks good! Thank you for the fix.

2024-09-17 11:19 UTC, merged