[Feature] --use-geth-block-processor to force go-ethereum/core.ApplyMessage
Fantom-foundation/Aida pull request #1171
Opened 2024-09-23 10:14 UTC by rpl-ffl

Added a flag `--use-geth-block-processor` to force use `go-ethereum/core.ApplyMessage` instead of  `go-opera/evmcore.ApplyMessage`.

Currently effective only for `aida-vm`.

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

2024-09-24 08:24 UTC, cabrador requested changes

2024-09-24 08:24 UTC, cabrador commented on utils/config.go
> +	log.Noticef("Forced geth block processor?: %v", cfg.UseGethBlockProcessor)
```suggestion
	log.Noticef("Forced geth block processor: %v", cfg.UseGethBlockProcessor)
```

2024-09-24 08:24 UTC, cabrador commented on executor/transaction_processor.go
> +	}
I dont think this is enough.
I believe you need to use `ApplyMessage` from `core` as well. 
I think the right approach is to create a new processor - rename this one to `aidaSonicProcessor` and create new one named `aidaGethProcessor`. Wdyt?

2024-09-24 08:48 UTC, cabrador commented on executor/transaction_processor.go
> +	}
Oh you use correct `ApplyMessage`. I wrongly read the code, mb. Nevertheless we should still split the two processors imo.

2024-09-25 09:23 UTC, wsodsong commented on cmd/aida-vm/main.go
> +			&utils.UseGethTxProcessorFlag,
Since txProcessor is called by most of the tools. I would imaging that `aida-vm-sdb substate` or `aida-vm-sdb eth-tests` would need this flag as well.

2024-09-26 11:34 UTC, matejmode submitted a review, later dismissed

2024-10-01 12:53 UTC, cabrador approved these changes
Thanks again for helping!

2024-10-01 12:54 UTC, merged