Matej/experimental/protobuf vm sdb
Fantom-foundation/Aida pull request #1193
Opened 2024-10-07 14:41 UTC by matejmode

## Description
Enable `aida-vm-sdb` to run on geth apply message, protobuf ethereum dataset with geth/lfvm evm.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

2024-10-23 12:11 UTC, wsodsong submitted a review, later dismissed

2024-10-23 13:50 UTC, cabrador requested changes
I dont really like the way you use `UpdateOnFailure` within `validateWorldState`. I believe there are some issues with an eth tx on our chain hence you must update the database but only when validating input.

I suggest you create two wrapper func
1) `validateEthInputWorldState()`
2) `validateEthOutputWorldState()`


and do the magic in the second func. wdyt?

2024-10-23 13:50 UTC, cabrador commented on executor/extension/validator/eth_state_test_error_validator_test.go
> +		t.Fatalf("pre-transaction must return success; %v", err)
```suggestion
		t.Fatalf("unexpected error: %v", err)
```

2024-10-23 13:50 UTC, cabrador commented on executor/extension/validator/eth_state_test_error_validator_test.go
> +	}
You should check that correct error has been returned.

2024-10-23 13:50 UTC, cabrador commented on executor/extension/validator/utils.go
> +func validateWorldState(cfg *utils.Config, db state.VmStateDB, expectedAlloc txcontext.WorldState, isPreTransaction bool, log logger.Logger) error {
Adding parameter called `isPreTransaction bool` and passing `cfg.UpdateOnFailure` is not a good idea.

2024-10-23 13:50 UTC, cabrador commented on executor/extension/validator/utils.go
> +			err = doSubsetValidation(expectedAlloc, db, cfg.UpdateOnFailure)
nit: rename to `doSubsetValidationOpera/Sonic`?

2024-10-24 18:39 UTC, matejmode commented on executor/extension/validator/utils.go
> +func validateWorldState(cfg *utils.Config, db state.VmStateDB, expectedAlloc txcontext.WorldState, isPreTransaction bool, log logger.Logger) error {
Renamed to `updateOnFailure`.

2024-10-24 18:43 UTC, matejmode commented
> I dont really like the way you use `UpdateOnFailure` within `validateWorldState`. I believe there are some issues with an eth tx on our chain hence you must update the database but only when validating input.
> 
> I suggest you create two wrapper func
> 
>     1. `validateEthInputWorldState()`
> 
>     2. `validateEthOutputWorldState()`
> 
> 
> and do the magic in the second func. wdyt?

This will be done as part of https://github.com/Fantom-foundation/Aida/issues/1211

2024-10-25 06:35 UTC, cabrador commented
> > I dont really like the way you use `UpdateOnFailure` within `validateWorldState`. I believe there are some issues with an eth tx on our chain hence you must update the database but only when validating input.
> > I suggest you create two wrapper func
> > ```
> > 1. `validateEthInputWorldState()`
> > 
> > 2. `validateEthOutputWorldState()`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and do the magic in the second func. wdyt?
> 
> This will be done as part of #1211

If you dont want to do it now, you should atleast remove `cfg` from `validateWorldState` a pass the necessary values instead of config

2024-10-28 20:18 UTC, matejmode commented
> `validateWorldState`

There is still `chainId` and `StateValidationMode` read from `cfg` as well and I can't simply decide whether to overwrite the variable at each call without redundantly checking the `chainId`.

2024-10-29 12:16 UTC, cabrador commented
> > `validateWorldState`
> 
> There is still `chainId` and `StateValidationMode` read from `cfg` as well and I can't simply decide whether to overwrite the variable at each call without redundantly checking the `chainId`.

Im not following, why dont you just pass `chainId` itself instead of `utils.Config`?

2024-10-31 07:12 UTC, wsodsong requested changes

2024-10-31 07:12 UTC, wsodsong commented on executor/extension/validator/utils.go
> +func fixEthereumExceptions(s executor.State[txcontext.TxContext], db state.VmStateDB, isPreTransaction bool) error {
Fix `Exception` suggests modification of error code or `throw` exceptions. It would be clear to have a name suggesting modifications to the database. Something like EthereumDbCorrection or UpdateEthereumDb.

2024-10-31 07:12 UTC, wsodsong commented on executor/extension/validator/utils.go
> +		if overwriteEverything || balance.Cmp(accBalance) < 0 || (slices.Contains(params.DAODrainList(), addr) && accBalance.Eq(uint256.NewInt(0))) {
nit: split line?

2024-10-31 07:12 UTC, wsodsong commented on cmd/aida-vm-sdb/run_substate.go
> +		statedb.MakeTransactionEventEmitter[txcontext.TxContext](),
I want to confirm with you the expected behaviour:
If Ethereum chain ID

Pre transaction EthereumExceptionUpdator
-  Make correction to balance or other special conditions

Pre transaction MakeLiveDbValidator
- If update-on-failure pre/all, apply differences
- else, return error

Pre transaction MakeTransactionEventEmitter
- BeginTransaction

Post transaction MakeTransactionEventEmitter
- EndTransaction

Post transaction MakeLiveDbValidator
- If update-on-failure post/all, apply differences
- else, return error

*Post transaction EthereumExceptionUpdator*
-  Make correction to balance or other special conditions

Is the order correct? Also is PostTransaction of EthereumExceptionUpdator necessary? I know the usecase of it.

2024-11-04 03:17 UTC, wsodsong commented on executor/extension/validator/eth_state_test_error_validator_test.go
> +func TestEthStateTestValidator_PreBlockEthereumReturnsSuccessBalanceFix(t *testing.T) {
This test seems to belong to `transaction_validator_test.go` rather than here. This is a test of ethereum tests which is not the target of your change.

2024-11-04 08:40 UTC, cabrador requested changes
I think we should merge the `updaters` into a single file

2024-11-04 08:40 UTC, cabrador commented on executor/extension/validator/eth_state_test_error_validator_test.go
`eth_state_test_error_validator` should only be used by `eth-state-tests`. Nevertheless, this PR does not seem to add any changes to this extension, so why do you add these tests?

2024-11-04 08:40 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updator.go
nit: `updator` -> `updater`

2024-11-04 08:40 UTC, cabrador commented on executor/extension/validator/ethereum_pre_transaction_updator.go
I think merging the updaters into one file would look better.

2024-11-04 08:40 UTC, cabrador commented on executor/extension/validator/transaction_validator.go
> +	if strings.ToLower(v.cfg.UpdateOnFailure) == "all" || strings.ToLower(v.cfg.UpdateOnFailure) == "pre" {
calling `ToLower` two times every tx is a bit expensive. I would call `ToLower` while assigning to the config itself, here you will be 100% sure its lowercase...

2024-11-04 08:40 UTC, cabrador commented on executor/extension/validator/transaction_validator.go
> +		if strings.ToLower(v.cfg.UpdateOnFailure) == "all" || strings.ToLower(v.cfg.UpdateOnFailure) == "post" {
same as above

2024-11-04 08:40 UTC, cabrador commented on executor/extension/validator/utils.go
> +var ethereumLfvmBlockExceptions = []int{13803456, 14340503, 14953169, 15025981, 15427798, 15445481}
I would make this a map[int]struct{}{} - it reduced the time complexity

2024-11-06 10:28 UTC, matejmode commented on executor/extension/validator/ethereum_pre_transaction_updator.go
after discussion will be kept as two separate extensions

2024-11-06 11:20 UTC, wsodsong commented on executor/extension/validator/utils.go
> +
The list of blocks would make more sense to be in the ethereum post extension. The functions in utils is kept with as few conditions as possible.

2024-11-06 11:20 UTC, wsodsong commented on executor/extension/validator/utils.go
> +	var overwriteEverything = false
`overwriteEverything` -> `overwriteAccount`. The term Everything is too vague.

2024-11-08 00:31 UTC, matejmode commented
I have reverted the `update-on-failure` related changes and they will be part of another PR.

2024-11-08 05:11 UTC, wsodsong reviewed
Looks good overall. Test files for the new extensions are missing.

2024-11-08 05:11 UTC, wsodsong commented on executor/extension/validator/ethereum_post_transaction_updater.go
a test file is missing.

2024-11-08 05:11 UTC, wsodsong commented on executor/extension/validator/ethereum_pre_transaction_updater.go
a test file is missing.

2024-11-08 05:11 UTC, wsodsong commented on executor/extension/validator/utils.go
> +		}
This logic can be moved `ethereum_post_transaction`.

2024-11-08 05:11 UTC, wsodsong commented on executor/extension/validator/ethereum_post_transaction_updater.go
> +	return updateEthereumDb(state, ctx, false)
Should check for block number here. If not in `ethereumLfvmBlockExceptions`, don't update DB and retrun nil.
a pointer to Input/Output substate may be passed instaed of `isPreTransaction` boolean. This way, extension specific code is kept within its extension.

2024-11-08 16:02 UTC, cabrador reviewed
I think it looks good, I have some minor comments though.

2024-11-08 16:02 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater.go
> +// Starting with the Shanghai revision and eip-3860 this was fixed
Could you explain why the blocks fail and why its correct that they fail?

2024-11-08 16:02 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater.go
> +	if cfg.ChainID != utils.EthereumChainID {
I would also add a condition that `VmImpl == "lfvm"` - we should not apply the fixes when running with geth vm right?

2024-11-08 16:02 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater.go
> +}
nit: could you please move the struct definition right after the factory func and PreRun above PostTransaction?

2024-11-08 16:02 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater.go
> +// Starting with the Shanghai revision and eip-3860 this was fixed
I would also move the map to `utils` file in this package

2024-11-08 16:02 UTC, cabrador commented on executor/extension/validator/ethereum_pre_transaction_updater.go
> +// PreTransaction validates fixes InputSubstate ethereum exceptions in given substate
```suggestion
// PreTransaction fixes InputSubstate ethereum exceptions in given substate
```

2024-11-08 16:02 UTC, cabrador commented on executor/extension/validator/utils.go
> +func updateEthereumDb(s executor.State[txcontext.TxContext], ctx *executor.Context, isPreTransaction bool) error {
I think the name is misleading. Afaik we are not updating `EthereumDb` right?

2024-11-11 09:21 UTC, matejmode commented on executor/extension/validator/ethereum_post_transaction_updater.go
> +// Starting with the Shanghai revision and eip-3860 this was fixed
I moved all interactions with `ethereumLfvmBlockExceptions` to `ethereumDbPostTransactionUpdater` therefore it can be kept in the same file.

2024-11-12 00:40 UTC, matejmode commented on executor/extension/validator/utils.go
> +func updateEthereumDb(s executor.State[txcontext.TxContext], ctx *executor.Context, isPreTransaction bool) error {
how about `fixStateDbOnEthereum` ?

2024-11-12 07:33 UTC, cabrador commented on executor/extension/validator/utils.go
> +func updateEthereumDb(s executor.State[txcontext.TxContext], ctx *executor.Context, isPreTransaction bool) error {
I thought about `fixEthereumExceptions`. Im terrible at naming variables tho, maybe @wsodsong has better idea

2024-11-12 07:39 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +}
nit: simpler
```suggestion
func getExceptionBlock() int {
	for key := range ethereumLfvmBlockExceptions {
		return key
	}
}
```

2024-11-12 07:39 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +func TestEthereumPostTransactionUpdator_Skips(t *testing.T) {
Updator -> Updater

2024-11-12 07:39 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +func TestEthereumPostTransactionUpdator_OverwriteAccount(t *testing.T) {
Updator -> Updater

2024-11-12 07:39 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +func TestEthereumPostTransactionUpdator_Skips(t *testing.T) {
Im not really sure what is this test supposed to do. Both test cases have same outcome. Could you maybe add detailed name? `Skips` is not really self-explanatory

2024-11-13 00:09 UTC, matejmode commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +func TestEthereumPostTransactionUpdator_Skips(t *testing.T) {
`TestEthereumPostTransactionUpdator_Skips` wraps these two tests https://github.com/Fantom-foundation/Aida/blob/68b92d9e1711dcfc71f8d8956576bb05db1875ce/executor/extension/validator/ethereum_post_transaction_updater_test.go#L18-L33

2024-11-14 05:43 UTC, wsodsong commented on executor/extension/validator/ethereum_post_transaction_updater.go
> +var ethereumLfvmBlockExceptions = map[int]struct{}{13803456: {}, 14340503: {}, 14953169: {}, 15025981: {}, 15427798: {}, 15445481: {}}
Can you please add `15445161` to the list as well?

2024-11-14 05:43 UTC, wsodsong commented on ethtest/state_test_context.go
> +	return NewWorldState(s.outputState)
@matejmode Ethereum test (not to confuse with ethereum substate test), doesn't use substate as its input. New extensions introduced in this PR also not used by ethereum test (cmd/aida-vm-sdb/run_eth.go). I am a bit confused why this file should be modified. 

@cabrador can you please confirm whether this has any impact on Ethereum tests?

2024-11-14 05:43 UTC, wsodsong commented on ethtest/mock_data.go
This file a mock data for ethereum test executed by `run_eth.go`. Your tests aim for `run_substate.go`. I don't think this is the correct place.

2024-11-14 05:43 UTC, wsodsong commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +func TestEthereumPostTransactionUpdater_Skips(t *testing.T) {
nit: please name the name more clear on what is `skipped`?

2024-11-14 05:43 UTC, wsodsong commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +
Please add a test case where a block which is not in the list is not skipped?

2024-11-14 05:43 UTC, wsodsong commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +	}
nit: ethereumLfvmBlockExceptions[0] ?

For loop is unnecessary when the very first value is returned.

2024-11-14 05:43 UTC, wsodsong commented on executor/extension/validator/ethereum_pre_transaction_updater_test.go
> +func TestEthereumPreTransactionUpdater_FixBalance(t *testing.T) {
```suggestion
func TestEthereumPreTransactionUpdater_FixBalanceWhenNewBalanceIsHigher(t *testing.T) {
```

2024-11-14 05:43 UTC, wsodsong commented on executor/extension/validator/utils.go
> +func fixEthereumExceptions(alloc txcontext.WorldState, db state.StateDB, overwriteAccount bool) error {
```suggestion
func UpdateStateDbOnEthereumChain(alloc txcontext.WorldState, db state.StateDB, overwriteAccount bool) error {
```

2024-11-14 11:46 UTC, matejmode commented on ethtest/state_test_context.go
> +	return NewWorldState(s.outputState)
I separated it from Ethereum tests txContext

2024-11-14 11:55 UTC, matejmode commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +func TestEthereumPostTransactionUpdater_Skips(t *testing.T) {
`TestEthereumPostTransactionUpdater_SkippedExtensionBecauseOfWrongConditions` ?

2024-11-14 12:04 UTC, matejmode commented on ethtest/mock_data.go
I created my own createTestTransaction using substate

2024-11-15 06:11 UTC, wsodsong commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +func TestEthereumPostTransactionUpdater_Skips(t *testing.T) {
Sound better!

2024-11-15 06:17 UTC, wsodsong commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +			err := ext.PostTransaction(st, ctx)
It should be checked whether the state got updated in this test.

2024-11-15 06:18 UTC, wsodsong commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +	}
Here as well. The current test doesn't seem to confirm that StateDB remains the same.

2024-11-15 09:34 UTC, wsodsong submitted a review, later dismissed

2024-11-15 14:04 UTC, matejmode commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +	}
no need because mock interface would have had been called with stateDb changing methods and failed the test.

2024-11-16 07:17 UTC, cabrador submitted a review, later dismissed
Looks good. Thanks a lot for this work!

2024-11-16 07:17 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater.go
> +// ethereumLfvmBlockzExceptions LFVM uses a uint16 program counter with a range from 0 to 65535.
```suggestion
// ethereumLfvmBlocksExceptions LFVM uses a uint16 program counter with a range from 0 to 65535.
```

2024-11-16 07:17 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater.go
> +// Starting with the Shanghai revision and eip-3860 this was fixed
I also think better documentation is necessary for this global

2024-11-16 07:17 UTC, cabrador commented on executor/extension/validator/ethereum_post_transaction_updater_test.go
> +	}
Since its a map, you cannot do that. Also this element is random.

2024-11-16 07:17 UTC, cabrador commented on executor/extension/validator/ethereum_pre_transaction_updater.go
> +	return updateStateDbOnEthereumChain(state.Data.GetInputState(), ctx.State, false)
Why dont we need to check the block number here?

2024-11-16 07:17 UTC, cabrador commented on executor/extension/validator/ethereum_pre_transaction_updater.go
> +	return updateStateDbOnEthereumChain(state.Data.GetInputState(), ctx.State, false)
My guess is input is always wrong?

2024-11-17 17:39 UTC, matejmode commented on executor/extension/validator/ethereum_pre_transaction_updater.go
> +	return updateStateDbOnEthereumChain(state.Data.GetInputState(), ctx.State, false)
our dataset doesn't have gas rewards therefore balance can be larger at preTrasaction.

2024-11-18 03:42 UTC, wsodsong approved these changes

2024-11-18 09:05 UTC, cabrador approved these changes

2024-11-18 13:20 UTC, merged