Eliminate dependency to former Sonic EVM implementation
Fantom-foundation/Aida pull request #1203
Opened 2024-10-10 19:33 UTC by HerbertJordan

## Description

Remove dependency to eliminated Sonic EVM implementation. The default EVM implementation is now the one provided by go-ethereum-sonic.

The new supported EVM implementation are:
- `opera` or default: uses the EVM implementation of `go-ethereum-sonic` in a Fantom compatible setup
- `ethereum`: uses the EVM implementation of `go-ethereum-sonic` in a Ethereum compatible setup
- `floria`: uses the EVM implementation of Tosca

The exchange of the EVM resulted in the change of order of state DB accesses. These changes affected several unit tests in the `cmd` directory. Some of those seemed to have been broken. 

In particular, the test `TestVmSdb_Substate_ValidationDoesNotFailOnValidTransaction` was not testing running a valid transaction. As part of fixing the expected StateDB accesses, this was corrected such that now the processing of the transaction succeeds.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

2024-10-11 09:18 UTC, cabrador submitted a review, later dismissed

2024-10-14 08:55 UTC, cabrador requested changes
Your change to error handling in `processRegularTx` breaks `geth-tests` We should not return this error as it must be checked by the validator.

2024-10-14 08:55 UTC, cabrador commented on executor/transaction_processor.go
> +	}
I dont think we should return this error but rather use the condition on line 354 - this is key especially for ethereum-tests

This should be the correct implementation:

```suggestion
	var msgResult messageResult
	var gasPool = new(core.GasPool)
	gasPool.AddGas(inputEnv.GetGasLimit())
	executionResult, err := core.ApplyMessage(evm, msg, gasPool)
	if err != nil {
		// if transaction fails, revert to the first snapshot.
		db.RevertToSnapshot(snapshot)
		finalError = errors.Join(fmt.Errorf("block: %v transaction: %v", block, tx), err)
	} else {
		msgResult = messageResult{
			failed:     executionResult.Failed(),
			returnData: executionResult.Return(),
			gasUsed:    executionResult.UsedGas,
			err:        executionResult.Err,
		}
	}

```

2024-10-14 08:55 UTC, cabrador commented on executor/transaction_processor.go
> +	msgResult := messageResult{
I dont think we should return this error but rather use the condition on line 354 - this is key especially for ethereum-tests

2024-10-15 04:43 UTC, wsodsong approved these changes

2024-10-15 10:15 UTC, cabrador approved these changes

2024-10-15 10:57 UTC, merged